### ISSUE TITLE
release 0.6.1 to CRAN for knitr-like text formatting

### ISSUE THREAD

**Issue by bquast** [yihui/highr#5]
We had a discussion yesterday here on how to do knitr-like formatting inline:

https://stackoverflow.com/questions/50715512/knitr-like-inline-code-formatting/50719628?noredirect=1#comment88449851_50719628

Based on your previous Q&A on doing the same in rmarkdown.

Both require highr 0.6.1, this functionality is quite useful, it would be great if this could be available from CRAN.

**Comment by yihui** [comment]
I will do it soon. Thanks!

**Comment by yihui** [comment]
Done: https://cran.rstudio.com/web/packages/highr/
