### ISSUE TITLE
R >=3.2.3 support issues

### ISSUE THREAD

**Issue by DavisVaughan** [yihui/highr#6]
Hi @yihui,

I see that you just bumped the required R version to >= 3.2.3. Unfortunately since knitr imports this package, this means that my R 3.1 builds on travis don't work anymore. See [here](https://travis-ci.org/tidymodels/probably/jobs/509537788#L2136). (I just cleared the travis cache on this package, which is why I got the error as it tried to pull in a fresh version of highr). 

I see [this commit](https://github.com/yihui/highr/commit/2d6768fa113660461e216304147ac7c27303d9f6) where you remove your previous hack. Is there any way we can keep it or improve it to keep 3.1 support? Currently, tidyverse packages try and support R >=3.1. When 3.6 releases we will probably drop support for 3.1 (which will be a welcome change). But in the meantime, I think this is going to affect a lot of our travis builds.

**Comment by yihui** [comment]
R 3.6.0 prereleases are coming in five days, and the final release is in about a month: http://developer.r-project.org/

R 3.2.3 was released on 2015-12-10 (3 years and 3 months ago). R 3.1.3 was released on 2015-03-09 (only 9 months apart). I wonder how many users are still stuck in R 3.1.3-3.2.2. Has anyone done a quick analysis from the CRAN logs?

Usually I tend not to support such old versions of R, but if it is really big trouble for you, I can certainly reconsider it.

**Comment by DavisVaughan** [comment]
I think you make a good point. Like you pointed out, I also found out right after I posted this that 3.6 releases in a month. I didn't know it was so soon from now. I think I'm fine with weaning my packages off 3.1 over the next month if I hit more errors from this. Thanks!

**Comment by yihui** [comment]
Sounds perfect!
