### ISSUE TITLE
Unable to load highr package

### ISSUE THREAD

**Issue by march3032** [yihui/highr#7]
i installed R-3.2.2 in my linux,but cannot load highr_0.8.tar.gz or highr_0.7.1.tar.gz by R CMD INSTALL either package , what can i do except uninstall R-3.2.2 and reinstall the higher version of R

**Comment by march3032** [comment]
my linux can not access to internet ,so i install the package by R CMD INSTALL source package

**Comment by yihui** [comment]
R <= 3.2.2 is not supported by the current version of **highr**: https://github.com/yihui/highr/blob/42547f09d58e78e70349a8893ff04e6c52d43623/DESCRIPTION#L13-L14

You have to upgrade R, or install lower versions of **highr**.

**Comment by march3032** [comment]
> R <= 3.2.2 is not supported by the current version of **highr**:
> 
> [highr/DESCRIPTION](https://github.com/yihui/highr/blob/42547f09d58e78e70349a8893ff04e6c52d43623/DESCRIPTION#L13-L14)
> 
> Lines 13 to 14 in [42547f0](/yihui/highr/commit/42547f09d58e78e70349a8893ff04e6c52d43623)
> 
>  Depends: 
>      R (>= 3.2.3) 
> You have to upgrade R, or install lower versions of **highr**.

i know this but how can i upgrade my Rversion ,my linux cannot access to internet and im a newhand about r installation ,can i use R CMD UPDATE a higher R version sourcepackage to upgrade R? also i cannot find lower version of highr

**Comment by march3032** [comment]
> R <= 3.2.2 is not supported by the current version of **highr**:
> 
> [highr/DESCRIPTION](https://github.com/yihui/highr/blob/42547f09d58e78e70349a8893ff04e6c52d43623/DESCRIPTION#L13-L14)
> 
> Lines 13 to 14 in [42547f0](/yihui/highr/commit/42547f09d58e78e70349a8893ff04e6c52d43623)
> 
>  Depends: 
>      R (>= 3.2.3) 
> You have to upgrade R, or install lower versions of **highr**.

i find it(highr lower version)   thanku bro！
